name = "Rizmatazz"
license = "GPL-3.0-or-later"
baseURL = 'http://localhost:8000'
languageCode = 'en-us'
title = '11th SCZ IAPSM Conference Ratlam'

[params]
  theme = "Theme of SCZ IAPSM 25 Conference, Ratlam"
  author = "Dr. Rizwan Ishak"