name = "Rizmatazz"
license = "GPL-3.0-or-later"
baseURL = 'http://localhost:8000'
languageCode = 'en-us'
title = '11th SCZ IAPSM Conference Ratlam'

[params]
  theme = "REVITALISING PUBLIC HEALTH: UNIFYING EFFORTS THROUGH INNOVATION AND COLLABORATION"
  author = "Dr. Rizwan Ishak"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
